spring.application.name=proj-Ptut
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Play'NRide
spring.datasource.username=postgres
spring.datasource.password=Linasaid1977

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port (optionnel)
server.port=8080
jwt.secret=KfC1t8e8qG9sF5H7vA2pQ0L1mZ3nX4Y6aB7cD8eF9gH0iJ1k
jwt.expirationMs=3600000
spring.security.user.name=admin
spring.security.user.password=admin